### ISSUE TITLE
Add a key/legend to the map images

### ISSUE THREAD

**Issue by schnuerle** [beamalsky/chivaxbot#16]
I love this work and had a quick thought seeing the final maps on Twitter.

Could you add a small key that shows what the color ranges mean? Not only the values, but also that the darker colors mean higher counts? It may not be clear to people who don't know the city/data already.

https://twitter.com/ChiVaxBot/status/1353531330231984130

**Comment by crunes** [comment]
Thanks for the feedback, @schnuerle - we've received lots of requests to add a key/legend and are looking into it!

**Comment by beamalsky** [comment]
Thanks for the note @schnuerle! This should be live next time the bot tweets tonight. We'd gone back and forth on this and didn't want to clutter the image, but from all the feedback we've gotten it's clear that including the key is the right move.

**Comment by schnuerle** [comment]
Looking good! https://twitter.com/ChiVaxBot/status/1353885791676739585
