### ISSUE TITLE
Create a pinned tweet, threading all tweets to-date

### ISSUE THREAD

**Issue by crunes** [beamalsky/chivaxbot#20]
A suggestion from https://twitter.com/jwitmer/status/1354250361691889666?s=21

**Comment by beamalsky** [comment]
This would be possible code-wise, but I'm hesitant to clutter up the bot's page. I think threads are harder to read and less likely to pop up on people's TLs. What do you think?

**Comment by crunes** [comment]
I've thought about it some more, and I think you're right - the nice thing about the bot is that the most updated maps will always be at the top, and if folks want to see older maps, they can scroll down. Having a pinned tweet of the maps from some arbitrary date might be confusing and might encourage users to interact with older maps.
