### ISSUE TITLE
Figure out when datasets update, when to post tweet

### ISSUE THREAD

**Issue by crunes** [beamalsky/chivaxbot#5]

**Comment by crunes** [comment]
I looked through the descriptions in the Chicago Data Portal, but I didn't see anything about update times so I reached out to the dataset owner (Jonathan Levy) to ask. Will update if I hear back!

**Comment by crunes** [comment]
@beamalsky just got an email from an epidemiologist confirming that both datasets should be updated by 7:30 pm every day. Maybe we can post the tweet at 8 PM? What do you think?

**Comment by beamalsky** [comment]
Sounds good to me! Thanks for investigating.

**Comment by beamalsky** [comment]
The bot should tweet at 8 tonight. I think we can close this for now?
