### ISSUE TITLE
Can we get custom illustrations for profile icon + header?

### ISSUE THREAD

**Issue by beamalsky** [beamalsky/chivaxbot#6]

**Comment by crunes** [comment]
I know they're working on hiring a new director for visuals so I don't know if it's best to wait until the new director starts in two weeks (Feb. 1) or if we want to put it in the pipeline ASAP. What do you think @beamalsky?

**Comment by beamalsky** [comment]
You know the SSW internal workings better than I do, but I was planning to bring this up with Jim tomorrow! Want to all check in then?
