### ISSUE TITLE
Workshop sentence

### ISSUE THREAD

**Issue by beamalsky** [beamalsky/chivaxbot#7]
Currently:

> Chicago is currently reporting 28,075 vaccinations and 4,313 total deaths from Covid-19.
> 
> Who is dying:               Who is vaccinated:

One alternate idea:

> Chicago is currently reporting 28,075 vaccinations, X% of the population.
> 
> Who is dying:               Who is vaccinated:

Curious to hear your thoughts on this, @crunes

**Comment by crunes** [comment]
I like the "share of the population" stat! I think it places the focus back on the city's progress with vaccines. I think it also makes the map more pointed.

**Comment by beamalsky** [comment]
I agree, the more I look at this! I'll switch it. The numbers we're using are for series completion, meaning for Pfizer and Moderna it's getting both shots. So how about: 

> Chicago is currently reporting 28,075 full vaccinations, X% of the population.
> 
> Who is dying: Who is vaccinated:

Lmk if you see other ways that could be clearer.

**Comment by beamalsky** [comment]
We could also just do: 

> XX% of Chicagoans are fully vaccinated, according to city data.

**Comment by crunes** [comment]
I like the brevity, but folks might not know what "fully vaccinated" means so we might want to elaborate a bit more. Maybe:

> XX% of Chicagoans are fully vaccinated (received both their first and second dose of the COVID-19 vaccine), according to city data.

It's a little wordy so super open to feedback!

**Comment by beamalsky** [comment]
The sticking point to me is that we might have a single-dose vaccine sometime in the not-so-distant future and I'd like to write a sentence that we wouldn't have to change, if possible. But I agree that "fully vaccinated" won't mean the same thing to everyone. I'll keep thinking!

**Comment by crunes** [comment]
What if we add a bit.ly link to the city's [COVID website's vaccine page](https://www.chicago.gov/city/en/sites/covid19-vaccine/home.html)? That should stay updated (hopefully) and can point people to the definition of "fully vaccinated". Then we can just use the "XX% of Chicagoans are fully vaccinated, according to city data" format!

**Comment by beamalsky** [comment]
Discussed on call: 

> Chicago is currently reporting ____ people fully vaccinated: ___% of the population

**Comment by crunes** [comment]
Just reviewed your PR and I think we can close this issue now, unless I'm forgetting something haha
