### ISSUE TITLE
Workshop Twitter bio

### ISSUE THREAD

**Issue by beamalsky** [beamalsky/chivaxbot#9]

**Comment by crunes** [comment]
Maybe something like: "Tracking who is dying from COVID-19 and who is fully vaccinated in Chicago, by @beamalsky & @SouthSideWeekly. Methodology & related reporting: bit.ly/chivaxbot", and the bit.ly link can go to the editor's note/launch page on the Weekly's website

This is 159/160 characters btw haha

**Comment by beamalsky** [comment]
I like it but you forgot yourself! What do you think about:

> Which Chicagoans are getting vaccinated? A bot by @beamalsky and @maerunes for @SouthSideWeekly. 

...and then we add the second sentence once that link is live?

> Methodology & related reporting: bit.ly/chivaxbot

**Comment by crunes** [comment]
I like it! I'll update the bio now.

**Comment by beamalsky** [comment]
Thank you! Just occurred to me... maybe we should add "Tweets daily" or "Tweets daily at 8pm"?

**Comment by crunes** [comment]
Added this to the bio as well! I had to shorten it a little to make sure we had the characters to add the link later, so now it's:

> Which Chicagoans are getting vaccinated? A bot by @beamalsky & @maerunes for @SouthSideWeekly. Tweets daily at 8pm. 

We can add "Methodology & reporting: bit.ly/chivaxbot" once that link is live
